# Copyright © 2026, Arm Limited and Contributors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# syntax=docker/dockerfile:1.7

# The workflow supplies both named contexts as immutable image references.
FROM toolchain AS generation

ENV INTRINSIC_CHUNKS_DIR=/chunks/intrinsic_chunks \
    YAML_DATA_DIR=/chunks/yaml_data \
    USEARCH_INDEX_FILENAME=/output/usearch_index.bin \
    METADATA_FILENAME=/output/metadata.json

COPY --from=chunks \
    /embedding-data/intrinsic_chunks/ \
    /chunks/intrinsic_chunks/
COPY --from=chunks \
    /embedding-data/yaml_data/ \
    /chunks/yaml_data/

WORKDIR /output

RUN --network=none \
    python /embedding-data/local_vectorstore_creation.py \
        --model-path /embedding-data/embedding-model \
    && rm -f embeddings_*.txt

FROM scratch AS vectorstore

COPY --from=generation \
    /embedding-data/embedding-model/ \
    /embedding-data/embedding-model/
COPY --from=generation \
    /output/metadata.json \
    /embedding-data/metadata.json
COPY --from=generation \
    /output/usearch_index.bin \
    /embedding-data/usearch_index.bin
